# Generated by Django 4.2.6 on 2023-12-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_posts', '0002_alter_author_birthday_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number_views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
